// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.read.scvi.flatbuffers.Titan.Model.Animaton;

@SuppressWarnings("unused")
public final class TrackFlag {
  private TrackFlag() { }
  public static final byte NONE = 0;
  public static final byte TrackFlag_Bool = 1;

  public static final String[] names = { "NONE", "TrackFlag_Bool", };

  public static String name(int e) { return names[e]; }
}

