// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.la.flatbuffers.Hayabusa.Model;

@SuppressWarnings("unused")
public final class IndexLayoutFormat {
  private IndexLayoutFormat() { }
  public static final long UINT8 = 0;
  public static final long UINT16 = 1;
  public static final long UINT32 = 2;
  public static final long UINT64 = 3;
}

