// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.la.flatbuffers.Hayabusa.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MaterialProperties extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static MaterialProperties getRootAsMaterialProperties(ByteBuffer _bb) { return getRootAsMaterialProperties(_bb, new MaterialProperties()); }
  public static MaterialProperties getRootAsMaterialProperties(ByteBuffer _bb, MaterialProperties obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MaterialProperties __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialMapper mappers(int j) { return mappers(new gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialMapper(), j); }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialMapper mappers(gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialMapper obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int mappersLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialMapper.Vector mappersVector() { return mappersVector(new gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialMapper.Vector()); }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialMapper.Vector mappersVector(gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialMapper.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public long res2() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long unk3() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.EmbeddedTRACM tracm() { return tracm(new gg.generations.imct.la.flatbuffers.Hayabusa.Model.EmbeddedTRACM()); }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.EmbeddedTRACM tracm(gg.generations.imct.la.flatbuffers.Hayabusa.Model.EmbeddedTRACM obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public long res5(int j) { int o = __offset(14); return o != 0 ? (long)bb.getInt(__vector(o) + j * 4) & 0xFFFFFFFFL : 0; }
  public int res5Length() { int o = __offset(14); return o != 0 ? __vector_len(o) : 0; }
  public IntVector res5Vector() { return res5Vector(new IntVector()); }
  public IntVector res5Vector(IntVector obj) { int o = __offset(14); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer res5AsByteBuffer() { return __vector_as_bytebuffer(14, 4); }
  public ByteBuffer res5InByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 4); }

  public static int createMaterialProperties(FlatBufferBuilder builder,
      int nameOffset,
      int mappersOffset,
      long res2,
      long unk3,
      int tracmOffset,
      int res5Offset) {
    builder.startTable(6);
    MaterialProperties.addRes5(builder, res5Offset);
    MaterialProperties.addTracm(builder, tracmOffset);
    MaterialProperties.addUnk3(builder, unk3);
    MaterialProperties.addRes2(builder, res2);
    MaterialProperties.addMappers(builder, mappersOffset);
    MaterialProperties.addName(builder, nameOffset);
    return MaterialProperties.endMaterialProperties(builder);
  }

  public static void startMaterialProperties(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addMappers(FlatBufferBuilder builder, int mappersOffset) { builder.addOffset(1, mappersOffset, 0); }
  public static int createMappersVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMappersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addRes2(FlatBufferBuilder builder, long res2) { builder.addInt(2, (int) res2, (int) 0L); }
  public static void addUnk3(FlatBufferBuilder builder, long unk3) { builder.addInt(3, (int) unk3, (int) 0L); }
  public static void addTracm(FlatBufferBuilder builder, int tracmOffset) { builder.addOffset(4, tracmOffset, 0); }
  public static void addRes5(FlatBufferBuilder builder, int res5Offset) { builder.addOffset(5, res5Offset, 0); }
  public static int createRes5Vector(FlatBufferBuilder builder, long[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addInt((int) data[i]); return builder.endVector(); }
  public static void startRes5Vector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endMaterialProperties(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MaterialProperties get(int j) { return get(new MaterialProperties(), j); }
    public MaterialProperties get(MaterialProperties obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

