// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.la.flatbuffers.Hayabusa.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MaterialTable extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static MaterialTable getRootAsMaterialTable(ByteBuffer _bb) { return getRootAsMaterialTable(_bb, new MaterialTable()); }
  public static MaterialTable getRootAsMaterialTable(ByteBuffer _bb, MaterialTable obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MaterialTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String fileNames(int j) { int o = __offset(6); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int fileNamesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public StringVector fileNamesVector() { return fileNamesVector(new StringVector()); }
  public StringVector fileNamesVector(StringVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialSwitches materialSwitches(int j) { return materialSwitches(new gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialSwitches(), j); }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialSwitches materialSwitches(gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialSwitches obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int materialSwitchesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialSwitches.Vector materialSwitchesVector() { return materialSwitchesVector(new gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialSwitches.Vector()); }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialSwitches.Vector materialSwitchesVector(gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialSwitches.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialProperties materialProperties(int j) { return materialProperties(new gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialProperties(), j); }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialProperties materialProperties(gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialProperties obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int materialPropertiesLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialProperties.Vector materialPropertiesVector() { return materialPropertiesVector(new gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialProperties.Vector()); }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialProperties.Vector materialPropertiesVector(gg.generations.imct.la.flatbuffers.Hayabusa.Model.MaterialProperties.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createMaterialTable(FlatBufferBuilder builder,
      int nameOffset,
      int fileNamesOffset,
      int materialSwitchesOffset,
      int materialPropertiesOffset) {
    builder.startTable(4);
    MaterialTable.addMaterialProperties(builder, materialPropertiesOffset);
    MaterialTable.addMaterialSwitches(builder, materialSwitchesOffset);
    MaterialTable.addFileNames(builder, fileNamesOffset);
    MaterialTable.addName(builder, nameOffset);
    return MaterialTable.endMaterialTable(builder);
  }

  public static void startMaterialTable(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addFileNames(FlatBufferBuilder builder, int fileNamesOffset) { builder.addOffset(1, fileNamesOffset, 0); }
  public static int createFileNamesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startFileNamesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addMaterialSwitches(FlatBufferBuilder builder, int materialSwitchesOffset) { builder.addOffset(2, materialSwitchesOffset, 0); }
  public static int createMaterialSwitchesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMaterialSwitchesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addMaterialProperties(FlatBufferBuilder builder, int materialPropertiesOffset) { builder.addOffset(3, materialPropertiesOffset, 0); }
  public static int createMaterialPropertiesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMaterialPropertiesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endMaterialTable(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MaterialTable get(int j) { return get(new MaterialTable(), j); }
    public MaterialTable get(MaterialTable obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

