// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.la.flatbuffers.Hayabusa.Model;

@SuppressWarnings("unused")
public final class NodeType {
  private NodeType() { }
  public static final long Transform = 0;
  public static final long Joint = 1;
  public static final long Locator = 2;
}

