// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.la.flatbuffers.Hayabusa.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class VertexAttributeLayout extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static VertexAttributeLayout getRootAsVertexAttributeLayout(ByteBuffer _bb) { return getRootAsVertexAttributeLayout(_bb, new VertexAttributeLayout()); }
  public static VertexAttributeLayout getRootAsVertexAttributeLayout(ByteBuffer _bb, VertexAttributeLayout obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VertexAttributeLayout __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.InputLayoutElement elements(int j) { return elements(new gg.generations.imct.la.flatbuffers.Hayabusa.Model.InputLayoutElement(), j); }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.InputLayoutElement elements(gg.generations.imct.la.flatbuffers.Hayabusa.Model.InputLayoutElement obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int elementsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.InputLayoutElement.Vector elementsVector() { return elementsVector(new gg.generations.imct.la.flatbuffers.Hayabusa.Model.InputLayoutElement.Vector()); }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.InputLayoutElement.Vector elementsVector(gg.generations.imct.la.flatbuffers.Hayabusa.Model.InputLayoutElement.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.VertexSize layoutSize(int j) { return layoutSize(new gg.generations.imct.la.flatbuffers.Hayabusa.Model.VertexSize(), j); }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.VertexSize layoutSize(gg.generations.imct.la.flatbuffers.Hayabusa.Model.VertexSize obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int layoutSizeLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.VertexSize.Vector layoutSizeVector() { return layoutSizeVector(new gg.generations.imct.la.flatbuffers.Hayabusa.Model.VertexSize.Vector()); }
  public gg.generations.imct.la.flatbuffers.Hayabusa.Model.VertexSize.Vector layoutSizeVector(gg.generations.imct.la.flatbuffers.Hayabusa.Model.VertexSize.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createVertexAttributeLayout(FlatBufferBuilder builder,
      int elementsOffset,
      int layoutSizeOffset) {
    builder.startTable(2);
    VertexAttributeLayout.addLayoutSize(builder, layoutSizeOffset);
    VertexAttributeLayout.addElements(builder, elementsOffset);
    return VertexAttributeLayout.endVertexAttributeLayout(builder);
  }

  public static void startVertexAttributeLayout(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addElements(FlatBufferBuilder builder, int elementsOffset) { builder.addOffset(0, elementsOffset, 0); }
  public static int createElementsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startElementsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addLayoutSize(FlatBufferBuilder builder, int layoutSizeOffset) { builder.addOffset(1, layoutSizeOffset, 0); }
  public static int createLayoutSizeVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startLayoutSizeVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endVertexAttributeLayout(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VertexAttributeLayout get(int j) { return get(new VertexAttributeLayout(), j); }
    public VertexAttributeLayout get(VertexAttributeLayout obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

