// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.read.la.flatbuffers.Hayabusa.Model;

@SuppressWarnings("unused")
public final class Attribute {
  private Attribute() { }
  public static final long NONE = 0;
  public static final long POSITION = 1;
  public static final long NORMAL = 2;
  public static final long TANGENT = 3;
  public static final long BINORMAL = 4;
  public static final long COLOR = 5;
  public static final long TEXCOORD = 6;
  public static final long BLEND_INDICES = 7;
  public static final long BLEND_WEIGHTS = 8;
}

