// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.read.la.flatbuffers.Hayabusa.Model;

@SuppressWarnings("unused")
public final class InputLayoutFormat {
  private InputLayoutFormat() { }
  public static final long NONE = 0;
  public static final long R8_G8_B8_A8_UNSIGNED_NORMALIZED = 20;
  public static final long R8_G8_B8_A8_UNSIGNED = 22;
  public static final long R16_G16_B16_A16_UNSIGNED_NORMALIZED = 39;
  public static final long R16_G16_B16_A16_FLOAT = 43;
  public static final long R32_G32_FLOAT = 48;
  public static final long R32_G32_B32_FLOAT = 51;
  public static final long R32_G32_B32_A32_FLOAT = 54;
}

