// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.read.la.flatbuffers.Hayabusa.Model;

@SuppressWarnings("unused")
public final class SpeciesSize {
  private SpeciesSize() { }
  public static final byte Size_S = 0;
  public static final byte Size_M = 1;
  public static final byte Size_L = 2;
  public static final byte Size_XL = 3;

  public static final String[] names = { "Size_S", "Size_M", "Size_L", "Size_XL", };

  public static String name(int e) { return names[e]; }
}

