// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.read.la.flatbuffers.Hayabusa.Model;

@SuppressWarnings("unused")
public final class UVWrapMode {
  private UVWrapMode() { }
  public static final long WRAP = 0;
  public static final long CLAMP = 1;
  public static final long MIRROR = 6;
  public static final long MIRROR_ONCE = 7;
}

