// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.read.scvi.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class EmbeddedTRACM extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static EmbeddedTRACM getRootAsEmbeddedTRACM(ByteBuffer _bb) { return getRootAsEmbeddedTRACM(_bb, new EmbeddedTRACM()); }
  public static EmbeddedTRACM getRootAsEmbeddedTRACM(ByteBuffer _bb, EmbeddedTRACM obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public EmbeddedTRACM __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int bytebuffer(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int bytebufferLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector bytebufferVector() { return bytebufferVector(new ByteVector()); }
  public ByteVector bytebufferVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer bytebufferAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer bytebufferInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createEmbeddedTRACM(FlatBufferBuilder builder,
      int bytebufferOffset) {
    builder.startTable(1);
    EmbeddedTRACM.addBytebuffer(builder, bytebufferOffset);
    return EmbeddedTRACM.endEmbeddedTRACM(builder);
  }

  public static void startEmbeddedTRACM(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addBytebuffer(FlatBufferBuilder builder, int bytebufferOffset) { builder.addOffset(0, bytebufferOffset, 0); }
  public static int createBytebufferVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createBytebufferVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startBytebufferVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endEmbeddedTRACM(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public EmbeddedTRACM get(int j) { return get(new EmbeddedTRACM(), j); }
    public EmbeddedTRACM get(EmbeddedTRACM obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

