// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.read.scvi.flatbuffers.Titan.Model;

@SuppressWarnings("unused")
public final class NodeType {
  private NodeType() { }
  public static final long Default = 0;
  public static final long Chained = 1;
  public static final long Floating = 2;
}

