// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.read.scvi.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class TRLTT extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static TRLTT getRootAsTRLTT(ByteBuffer _bb) { return getRootAsTRLTT(_bb, new TRLTT()); }
  public static TRLTT getRootAsTRLTT(ByteBuffer _bb, TRLTT obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TRLTT __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long res0() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public gg.generations.imct.read.scvi.flatbuffers.Titan.Model.LookupTable entries(int j) { return entries(new gg.generations.imct.read.scvi.flatbuffers.Titan.Model.LookupTable(), j); }
  public gg.generations.imct.read.scvi.flatbuffers.Titan.Model.LookupTable entries(gg.generations.imct.read.scvi.flatbuffers.Titan.Model.LookupTable obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int entriesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public gg.generations.imct.read.scvi.flatbuffers.Titan.Model.LookupTable.Vector entriesVector() { return entriesVector(new gg.generations.imct.read.scvi.flatbuffers.Titan.Model.LookupTable.Vector()); }
  public gg.generations.imct.read.scvi.flatbuffers.Titan.Model.LookupTable.Vector entriesVector(gg.generations.imct.read.scvi.flatbuffers.Titan.Model.LookupTable.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createTRLTT(FlatBufferBuilder builder,
      long res0,
      int entriesOffset) {
    builder.startTable(2);
    TRLTT.addEntries(builder, entriesOffset);
    TRLTT.addRes0(builder, res0);
    return TRLTT.endTRLTT(builder);
  }

  public static void startTRLTT(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addRes0(FlatBufferBuilder builder, long res0) { builder.addInt(0, (int) res0, (int) 0L); }
  public static void addEntries(FlatBufferBuilder builder, int entriesOffset) { builder.addOffset(1, entriesOffset, 0); }
  public static int createEntriesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startEntriesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endTRLTT(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishTRLTTBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedTRLTTBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TRLTT get(int j) { return get(new TRLTT(), j); }
    public TRLTT get(TRLTT obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

