// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.read.scvi.flatbuffers.Titan.Model;

@SuppressWarnings("unused")
public final class VertexAttribute {
  private VertexAttribute() { }
  public static final long NONE = 0;
  public static final long POSITION = 1;
  public static final long NORMAL = 2;
  public static final long TANGENT = 3;
  public static final long BINORMAL = 4;
  public static final long COLOR = 5;
  public static final long TEX_COORD = 6;
  public static final long BLEND_INDICES = 7;
  public static final long BLEND_WEIGHTS = 8;
  public static final long USER = 9;
  public static final long USER_ID = 10;
}

