// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.Gfbmdl;

@SuppressWarnings("unused")
public final class BoneType {
  private BoneType() { }
  public static final long NoSkinning = 0;
  public static final long HasSkinning = 1;
}

