// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

@SuppressWarnings("unused")
public final class Attribute {
  private Attribute() { }
  public static final int POSITION = 0;
  public static final int NORMAL = 1;
  public static final int BINORMAL = 2;
  public static final int TEXCOORD_0 = 3;
  public static final int TEXCOORD_1 = 4;
  public static final int TEXCOORD_2 = 5;
  public static final int TEXCOORD_3 = 6;
  public static final int COLOR_0 = 7;
  public static final int COLOR_1 = 8;
  public static final int COLOR_2 = 9;
  public static final int COLOR_3 = 10;
  public static final int GROUP_IDX = 11;
  public static final int GROUP_WEIGHT = 12;

  public static final String[] names = { "POSITION", "NORMAL", "BINORMAL", "TEXCOORD_0", "TEXCOORD_1", "TEXCOORD_2", "TEXCOORD_3", "COLOR_0", "COLOR_1", "COLOR_2", "COLOR_3", "GROUP_IDX", "GROUP_WEIGHT", };

  public static String name(int e) { return names[e]; }
}

