// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

@SuppressWarnings("unused")
public final class BillboardType {
  private BillboardType() { }
  public static final long None = 0;
  public static final long AxisY = 1;
  public static final long AxisXY = 2;
}

