// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

@SuppressWarnings("unused")
public final class Blend_Mode {
  private Blend_Mode() { }
  public static final long NONE = 0;
  public static final long ALPHA = 1;
  public static final long ADD = 2;
  public static final long SUBTRACT = 3;
  public static final long MULTIPLY = 4;
  public static final long PREMULTIPLY = 5;
  public static final long COUNT = 6;
}

