// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

@SuppressWarnings("unused")
public final class BoneType {
  private BoneType() { }
  public static final long Transform = 0;
  public static final long Joint = 1;
  public static final long Locator = 2;
  public static final long Transparency_Group = 3;
}

