// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Box extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Box __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 b1() { return b1(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3()); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 b1(gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 obj) { return obj.__assign(bb_pos + 0, bb); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 b2() { return b2(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3()); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 b2(gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 obj) { return obj.__assign(bb_pos + 12, bb); }

  public static int createBox(FlatBufferBuilder builder, float b1_x, float b1_y, float b1_z, float b2_x, float b2_y, float b2_z) {
    builder.prep(4, 24);
    builder.prep(4, 12);
    builder.putFloat(b2_z);
    builder.putFloat(b2_y);
    builder.putFloat(b2_x);
    builder.prep(4, 12);
    builder.putFloat(b1_z);
    builder.putFloat(b1_y);
    builder.putFloat(b1_x);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Box get(int j) { return get(new Box(), j); }
    public Box get(Box obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

