// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ColMesh extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static ColMesh getRootAsColMesh(ByteBuffer _bb) { return getRootAsColMesh(_bb, new ColMesh()); }
  public static ColMesh getRootAsColMesh(ByteBuffer _bb, ColMesh obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ColMesh __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long colId() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Box box() { return box(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.Box()); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Box box(gg.generations.imct.swsh.flatbuffers.GFLib.Model.Box obj) { int o = __offset(6); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startColMesh(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addColId(FlatBufferBuilder builder, long colId) { builder.addInt(0, (int) colId, (int) 0L); }
  public static void addBox(FlatBufferBuilder builder, int boxOffset) { builder.addStruct(1, boxOffset, 0); }
  public static int endColMesh(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ColMesh get(int j) { return get(new ColMesh(), j); }
    public ColMesh get(ColMesh obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

