// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

@SuppressWarnings("unused")
public final class Cull_Mode {
  private Cull_Mode() { }
  public static final long NONE = 0;
  public static final long BACK = 1;
  public static final long FRONT = 2;
}

