// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

@SuppressWarnings("unused")
public final class DataType {
  private DataType() { }
  public static final int _Float = 0;
  public static final int _HalfFloat = 1;
  public static final int _Byte = 2;
  public static final int _UByte = 3;
  public static final int _Short = 4;
  public static final int _UShort = 5;
  public static final int _Int = 6;
  public static final int _UInt = 7;
  public static final int _FixedPoint = 8;

  public static final String[] names = { "_Float", "_HalfFloat", "_Byte", "_UByte", "_Short", "_UShort", "_Int", "_UInt", "_FixedPoint", };

  public static String name(int e) { return names[e]; }
}

