// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

@SuppressWarnings("unused")
public final class DepthComparison {
  private DepthComparison() { }
  public static final long NEVER = 0;
  public static final long LESS = 1;
  public static final long LESSEQUAL = 2;
  public static final long GREATER = 3;
  public static final long NOTEQUAL = 4;
  public static final long GREATEREQUAL = 5;
  public static final long ALWAYS = 7;
}

