// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GFBCol extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static GFBCol getRootAsGFBCol(ByteBuffer _bb) { return getRootAsGFBCol(_bb, new GFBCol()); }
  public static GFBCol getRootAsGFBCol(ByteBuffer _bb, GFBCol obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GFBCol __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColString names(int j) { return names(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColString(), j); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColString names(gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColString obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int namesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColString.Vector namesVector() { return namesVector(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColString.Vector()); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColString.Vector namesVector(gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColString.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColMesh meshes(int j) { return meshes(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColMesh(), j); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColMesh meshes(gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColMesh obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int meshesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColMesh.Vector meshesVector() { return meshesVector(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColMesh.Vector()); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColMesh.Vector meshesVector(gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColMesh.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColShape shapes(int j) { return shapes(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColShape(), j); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColShape shapes(gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColShape obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int shapesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColShape.Vector shapesVector() { return shapesVector(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColShape.Vector()); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColShape.Vector shapesVector(gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColShape.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColOrder info() { return info(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColOrder()); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColOrder info(gg.generations.imct.swsh.flatbuffers.GFLib.Model.ColOrder obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createGFBCol(FlatBufferBuilder builder,
      int namesOffset,
      int meshesOffset,
      int shapesOffset,
      int infoOffset) {
    builder.startTable(4);
    GFBCol.addInfo(builder, infoOffset);
    GFBCol.addShapes(builder, shapesOffset);
    GFBCol.addMeshes(builder, meshesOffset);
    GFBCol.addNames(builder, namesOffset);
    return GFBCol.endGFBCol(builder);
  }

  public static void startGFBCol(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addNames(FlatBufferBuilder builder, int namesOffset) { builder.addOffset(0, namesOffset, 0); }
  public static int createNamesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startNamesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addMeshes(FlatBufferBuilder builder, int meshesOffset) { builder.addOffset(1, meshesOffset, 0); }
  public static int createMeshesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startMeshesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addShapes(FlatBufferBuilder builder, int shapesOffset) { builder.addOffset(2, shapesOffset, 0); }
  public static int createShapesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startShapesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addInfo(FlatBufferBuilder builder, int infoOffset) { builder.addOffset(3, infoOffset, 0); }
  public static int endGFBCol(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishGFBColBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedGFBColBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GFBCol get(int j) { return get(new GFBCol(), j); }
    public GFBCol get(GFBCol obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

