// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Instance extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static Instance getRootAsInstance(ByteBuffer _bb) { return getRootAsInstance(_bb, new Instance()); }
  public static Instance getRootAsInstance(ByteBuffer _bb, Instance obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Instance __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String mayaPath() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mayaPathAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer mayaPathInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String mayaName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer mayaNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer mayaNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Box b1() { return b1(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.Box()); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Box b1(gg.generations.imct.swsh.flatbuffers.GFLib.Model.Box obj) { int o = __offset(8); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Box b2() { return b2(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.Box()); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Box b2(gg.generations.imct.swsh.flatbuffers.GFLib.Model.Box obj) { int o = __offset(10); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.InstanceData data(int j) { return data(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.InstanceData(), j); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.InstanceData data(gg.generations.imct.swsh.flatbuffers.GFLib.Model.InstanceData obj, int j) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int dataLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.InstanceData.Vector dataVector() { return dataVector(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.InstanceData.Vector()); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.InstanceData.Vector dataVector(gg.generations.imct.swsh.flatbuffers.GFLib.Model.InstanceData.Vector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static void startInstance(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addMayaPath(FlatBufferBuilder builder, int mayaPathOffset) { builder.addOffset(0, mayaPathOffset, 0); }
  public static void addMayaName(FlatBufferBuilder builder, int mayaNameOffset) { builder.addOffset(1, mayaNameOffset, 0); }
  public static void addB1(FlatBufferBuilder builder, int b1Offset) { builder.addStruct(2, b1Offset, 0); }
  public static void addB2(FlatBufferBuilder builder, int b2Offset) { builder.addStruct(3, b2Offset, 0); }
  public static void addData(FlatBufferBuilder builder, int dataOffset) { builder.addOffset(4, dataOffset, 0); }
  public static int createDataVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startDataVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endInstance(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Instance get(int j) { return get(new Instance(), j); }
    public Instance get(Instance obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

