// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class InstanceData extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static InstanceData getRootAsInstanceData(ByteBuffer _bb) { return getRootAsInstanceData(_bb, new InstanceData()); }
  public static InstanceData getRootAsInstanceData(ByteBuffer _bb, InstanceData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public InstanceData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 instanceScale() { return instanceScale(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3()); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 instanceScale(gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 instanceRot() { return instanceRot(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3()); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 instanceRot(gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 obj) { int o = __offset(6); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 instancePos() { return instancePos(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3()); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 instancePos(gg.generations.imct.swsh.flatbuffers.GFLib.Model.Vec3 obj) { int o = __offset(8); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startInstanceData(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addInstanceScale(FlatBufferBuilder builder, int instanceScaleOffset) { builder.addStruct(0, instanceScaleOffset, 0); }
  public static void addInstanceRot(FlatBufferBuilder builder, int instanceRotOffset) { builder.addStruct(1, instanceRotOffset, 0); }
  public static void addInstancePos(FlatBufferBuilder builder, int instancePosOffset) { builder.addStruct(2, instancePosOffset, 0); }
  public static int endInstanceData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public InstanceData get(int j) { return get(new InstanceData(), j); }
    public InstanceData get(InstanceData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

