// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class LayerData extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static LayerData getRootAsLayerData(ByteBuffer _bb) { return getRootAsLayerData(_bb, new LayerData()); }
  public static LayerData getRootAsLayerData(ByteBuffer _bb, LayerData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public LayerData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long layerIndex() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public float mixFactor() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createLayerData(FlatBufferBuilder builder,
      long layerIndex,
      float mixFactor) {
    builder.startTable(2);
    LayerData.addMixFactor(builder, mixFactor);
    LayerData.addLayerIndex(builder, layerIndex);
    return LayerData.endLayerData(builder);
  }

  public static void startLayerData(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addLayerIndex(FlatBufferBuilder builder, long layerIndex) { builder.addInt(0, (int) layerIndex, (int) 0L); }
  public static void addMixFactor(FlatBufferBuilder builder, float mixFactor) { builder.addFloat(1, mixFactor, 0.0f); }
  public static int endLayerData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public LayerData get(int j) { return get(new LayerData(), j); }
    public LayerData get(LayerData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

