// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

@SuppressWarnings("unused")
public final class Pass {
  private Pass() { }
  public static final long DEFAULT = 0;
  public static final long PARTICLE = 1;
  public static final long ADDGLASS = 2;
  public static final long ALPGLASS = 3;
}

