// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SamplerState extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static SamplerState getRootAsSamplerState(ByteBuffer _bb) { return getRootAsSamplerState(_bb, new SamplerState()); }
  public static SamplerState getRootAsSamplerState(ByteBuffer _bb, SamplerState obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SamplerState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long filtermode() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long repeatU() { int o = __offset(6); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long repeatV() { int o = __offset(8); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public long repeat2() { int o = __offset(10); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.RGBA borderColor() { return borderColor(new gg.generations.imct.swsh.flatbuffers.GFLib.Model.RGBA()); }
  public gg.generations.imct.swsh.flatbuffers.GFLib.Model.RGBA borderColor(gg.generations.imct.swsh.flatbuffers.GFLib.Model.RGBA obj) { int o = __offset(12); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public float mipMapBias() { int o = __offset(14); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static void startSamplerState(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addFiltermode(FlatBufferBuilder builder, long filtermode) { builder.addInt(0, (int) filtermode, (int) 0L); }
  public static void addRepeatU(FlatBufferBuilder builder, long repeatU) { builder.addInt(1, (int) repeatU, (int) 0L); }
  public static void addRepeatV(FlatBufferBuilder builder, long repeatV) { builder.addInt(2, (int) repeatV, (int) 0L); }
  public static void addRepeat2(FlatBufferBuilder builder, long repeat2) { builder.addInt(3, (int) repeat2, (int) 0L); }
  public static void addBorderColor(FlatBufferBuilder builder, int borderColorOffset) { builder.addStruct(4, borderColorOffset, 0); }
  public static void addMipMapBias(FlatBufferBuilder builder, float mipMapBias) { builder.addFloat(5, mipMapBias, 0.0f); }
  public static int endSamplerState(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SamplerState get(int j) { return get(new SamplerState(), j); }
    public SamplerState get(SamplerState obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

