// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.swsh.flatbuffers.GFLib.Model;

@SuppressWarnings("unused")
public final class Unk {
  private Unk() { }
  public static final long s0 = 0;
  public static final long s1 = 7;
}

