// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.read.swsh.flatbuffers.Gfbmdl;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Struct;

import java.nio.ByteBuffer;

@SuppressWarnings("unused")
public final class BoneRigidData extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BoneRigidData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte unknown1() { return bb.get(bb_pos + 0); }

  public static int createBoneRigidData(FlatBufferBuilder builder, byte unknown1) {
    builder.prep(1, 1);
    builder.putByte(unknown1);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BoneRigidData get(int j) { return get(new BoneRigidData(), j); }
    public BoneRigidData get(BoneRigidData obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

