// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.read.swsh.flatbuffers.Gfbmdl;

@SuppressWarnings("unused")
public final class BufferFormat {
  private BufferFormat() { }
  public static final long Float = 0;
  public static final long HalfFloat = 1;
  public static final long Byte = 3;
  public static final long Short = 5;
  public static final long BytesAsFloat = 8;
}

