// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.read.swsh.flatbuffers.Gfbmdl;

@SuppressWarnings("unused")
public final class VertexType {
  private VertexType() { }
  public static final long Position = 0;
  public static final long Normal = 1;
  public static final long Binormal = 2;
  public static final long UV1 = 3;
  public static final long UV2 = 4;
  public static final long UV3 = 5;
  public static final long UV4 = 6;
  public static final long Color1 = 7;
  public static final long Color2 = 8;
  public static final long Color3 = 9;
  public static final long Color4 = 10;
  public static final long BoneID = 11;
  public static final long BoneWeight = 12;
}

