// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.scvi.flatbuffers.Titan.Model;

import com.google.flatbuffers.*;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class BoneEntry extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static BoneEntry getRootAsBoneEntry(ByteBuffer _bb) { return getRootAsBoneEntry(_bb, new BoneEntry()); }
  public static BoneEntry getRootAsBoneEntry(ByteBuffer _bb, BoneEntry obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BoneEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String slots(int j) { int o = __offset(6); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int slotsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public StringVector slotsVector() { return slotsVector(new StringVector()); }
  public StringVector slotsVector(StringVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public float unk3() { int o = __offset(8); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createBoneEntry(FlatBufferBuilder builder,
      int nameOffset,
      int slotsOffset,
      float unk3) {
    builder.startTable(3);
    BoneEntry.addUnk3(builder, unk3);
    BoneEntry.addSlots(builder, slotsOffset);
    BoneEntry.addName(builder, nameOffset);
    return BoneEntry.endBoneEntry(builder);
  }

  public static void startBoneEntry(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addSlots(FlatBufferBuilder builder, int slotsOffset) { builder.addOffset(1, slotsOffset, 0); }
  public static int createSlotsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSlotsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addUnk3(FlatBufferBuilder builder, float unk3) { builder.addFloat(2, unk3, 0.0f); }
  public static int endBoneEntry(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BoneEntry get(int j) { return get(new BoneEntry(), j); }
    public BoneEntry get(BoneEntry obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

