// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.scvi.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class LodIndex extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static LodIndex getRootAsLodIndex(ByteBuffer _bb) { return getRootAsLodIndex(_bb, new LodIndex()); }
  public static LodIndex getRootAsLodIndex(ByteBuffer _bb, LodIndex obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public LodIndex __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long unk0() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createLodIndex(FlatBufferBuilder builder,
      long unk0) {
    builder.startTable(1);
    LodIndex.addUnk0(builder, unk0);
    return LodIndex.endLodIndex(builder);
  }

  public static void startLodIndex(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addUnk0(FlatBufferBuilder builder, long unk0) { builder.addInt(0, (int) unk0, (int) 0L); }
  public static int endLodIndex(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public LodIndex get(int j) { return get(new LodIndex(), j); }
    public LodIndex get(LodIndex obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

