// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.scvi.flatbuffers.Titan.Model;

@SuppressWarnings("unused")
public final class MorphAttribute {
  private MorphAttribute() { }
  public static final long NONE = 0;
  public static final long POSITION = 1;
  public static final long MIN_LIMIT = 2;
  public static final long MAX_LIMIT = 3;
  public static final long USER_ID = 10;
}

