// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.scvi.flatbuffers.Titan.Model;

@SuppressWarnings("unused")
public final class PolygonType {
  private PolygonType() { }
  public static final long X8_Y8_Z8_UNSIGNED = 0;
  public static final long X16_Y16_Z16_UNSIGNED = 1;
  public static final long X32_Y32_Z32_UNSIGNED = 2;
  public static final long X64_Y64_Z64_UNSIGNED = 3;
}

