// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.scvi.flatbuffers.Titan.Model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Shader extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static Shader getRootAsShader(ByteBuffer _bb) { return getRootAsShader(_bb, new Shader()); }
  public static Shader getRootAsShader(ByteBuffer _bb, Shader obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Shader __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String shaderName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer shaderNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer shaderNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public gg.generations.imct.scvi.flatbuffers.Titan.Model.StringParameter shaderValues(int j) { return shaderValues(new gg.generations.imct.scvi.flatbuffers.Titan.Model.StringParameter(), j); }
  public gg.generations.imct.scvi.flatbuffers.Titan.Model.StringParameter shaderValues(gg.generations.imct.scvi.flatbuffers.Titan.Model.StringParameter obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int shaderValuesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public gg.generations.imct.scvi.flatbuffers.Titan.Model.StringParameter.Vector shaderValuesVector() { return shaderValuesVector(new gg.generations.imct.scvi.flatbuffers.Titan.Model.StringParameter.Vector()); }
  public gg.generations.imct.scvi.flatbuffers.Titan.Model.StringParameter.Vector shaderValuesVector(gg.generations.imct.scvi.flatbuffers.Titan.Model.StringParameter.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createShader(FlatBufferBuilder builder,
      int shaderNameOffset,
      int shaderValuesOffset) {
    builder.startTable(2);
    Shader.addShaderValues(builder, shaderValuesOffset);
    Shader.addShaderName(builder, shaderNameOffset);
    return Shader.endShader(builder);
  }

  public static void startShader(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addShaderName(FlatBufferBuilder builder, int shaderNameOffset) { builder.addOffset(0, shaderNameOffset, 0); }
  public static void addShaderValues(FlatBufferBuilder builder, int shaderValuesOffset) { builder.addOffset(1, shaderValuesOffset, 0); }
  public static int createShaderValuesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startShaderValuesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endShader(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Shader get(int j) { return get(new Shader(), j); }
    public Shader get(Shader obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

