// automatically generated by the FlatBuffers compiler, do not modify

package gg.generations.imct.scvi.flatbuffers.Titan.Model;

@SuppressWarnings("unused")
public final class Type {
  private Type() { }
  public static final long NONE = 0;
  public static final long R8_G8_B8_A8_UNSIGNED_NORMALIZED = 20;
  public static final long W8_X8_Y8_Z8_UNSIGNED = 22;
  public static final long X32_UINT = 36;
  public static final long X32_INT = 37;
  public static final long W16_X16_Y16_Z16_SIGNED_NORMALIZED = 39;
  public static final long W16_X16_Y16_Z16_FLOAT = 43;
  public static final long X32_Y32_FLOAT = 48;
  public static final long X32_Y32_Z32_FLOAT = 51;
  public static final long W32_X32_Y32_Z32_FLOAT = 54;
}

